# Generated by Django 5.2.5 on 2025-09-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UtilityApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PLCConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("port", models.IntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id",), name="unique_plc_connection"
                    )
                ],
            },
        ),
    ]
